[cerebrium.deployment]
name = "image-classifier-cerebrium"
python_version = "3.13"
docker_base_image_url = "debian:bookworm-slim"
include = ["*"]
exclude = ["./venv"]

[cerebrium.runtime.custom]
port = 8000
entrypoint = ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

[cerebrium.hardware]
cpu = 4
memory = 16.0
compute = "AMPERE_A10"
gpu_count = 1

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
replica_concurrency = 10
cooldown = 1800

[cerebrium.dependencies.pip]
uvicorn = "latest"
numpy="1.26.4"
Pillow="10.4.0"
fastapi="0.115.0"
onnx="1.16.2"
onnxruntime="1.20.0"
python-multipart="0.0.9"